export const activitySilly= [
  "playing pattycake",
  "having a tea party",
  "making funny faces",
  "trying to walk on stilts",
  "dressing up in silly costumes",
  "playing with Play-Doh",
  "doing a silly dance",
  "trying to balance a spoon on your nose",
  "doing a stand-up comedy routine",
  "having a water balloon fight",
  "doing a silly voice-over",
  "pretending to be a superhero",
  "playing charades",
  "telling jokes",
  "having a pillow fight",
  "doing a magic trick",
  "playing a prank on someone",
  "doing a trust fall",
  "having a food fight",
  "singing at the top of your lungs",
  "doing a handstand",
  "building a fort out of blankets",
  "having a Nerf gun war",
  "doing an impersonation",
  "doing a comedy sketch",
  "having a tickle fight",
  "doing a cartwheel",
];
